### ISSUE TITLE
Start creating Protoype (Basic Routing)

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#14]
- Attempt to develop a working prototype
- Nothing fancy, just basic routing

Victor
- [x] Mistral setup (or alternative)
- #28 

Dinuja
- [x] Cohere setup
- #32 

Alain/Laxit
- [x] Vertexai
- #30 

Laxit
- [x] Setup Requirements
- #33 

Kyle
- [x] Research into an alternative and setup
- #29

**Comment by TheVicBro** [comment]
Basic routing:

- Ex. 1+1
  - Text generation will not work
  - Open AI will cost the most

- Conditions:
  - Cost
  - Size of prompt
  - Availability
  - Speed
  - Size of response
  - Context

- How will the developer interface with our library

**Comment by laxitshahi** [comment]
This task also relates to #61 #62 #63
