### ISSUE TITLE
Familiarize and test LLM Proxy with open source repos

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#15]
Using the locally packages LLM proxy test on open source tools such as:
- GPT Engineer
- Other tools that you find

Realtes to #20

**Comment by dinuja9** [comment]
How to add LLMProxy to gpt-engineer repo:

In llmproxy do the following:
   1. Change `python-dotenv = "^1.0.0"` to `python-dotenv = ">=0.21.0"` do this by using the command `poetry add "python-dotenv==0.21.0"
   2. In the pyproject.toml, change `name = "llm-proxy"` to `name = "llmproxy"`
   3. Run `poetry build` to have the project ready to import into gpt-engineer

After, you need to do 1 or the other:
   1. Uninstall your current version of python if it isn't >= 3.10  and < 3.12, and install python version 3.11.0, or any version in 3.11
   2. Use pyenv to change the python version

In gpt-engineer:
   1. Run `poetry add llmproxy@<specify the path>`
           for example: `poetry add llmproxy@C:/Users/dinuj/Documents/LLM-Proxy/code`
   2. Run `poetry install`
   3. Run `poetry shell`

And you should now be able to run gpt-engineers

**Comment by dinuja9** [comment]
- There is some caching happening which is storing the user input from the terminal rather than looking at the prompt file
- internal.config.yml needs to change to a hashmap so we can package it properly
- check out clarity ai instead of gpt-eng

**Comment by laxitshahi** [comment]
Local testing complete
