### ISSUE TITLE
Research categorization benchmarking

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#153]
Research a way to better benchmark the categorization of prompts

Research a better way to benchmark different LLMs based on different categories of prompts:
1. You can find research papers and try to gather findings that point to a similar conclusion
2. You can create a "custom GPT" prompt to rank the output of different models
 - This would be done with the best model available (GPT-4)
 - You can also automate this to gather data for n number of tests
 - Since Victor has GPT, it may be possible to automate this task using javascript on the browser

This benchmarking can also be used as part of our test suites for testing.

References: 
- https://benchmarks.llmonitor.com/
- https://python.langchain.com/docs/guides/model_laboratory
- https://txt.cohere.com/evaluating-llm-outputs/
- https://research.aimultiple.com/large-language-model-evaluation/

**Comment by laxitshahi** [comment]
No longer doing this, we are just going to use leaderboard data:
https://huggingface.co/spaces/lmsys/chatbot-arena-leaderboard
