### ISSUE TITLE
Create a framework to test cost vs GPT

### ISSUE THREAD

**Issue by laxitshahi** [llm-proxy/llm-proxy#193]
Create a script, or integration test to compare the costs of using LLM Proxy vs purely GPT-4 (or GPT3.5)

**Comment by MohamedAhmed74** [comment]
Not full defined yet

![Image](https://github.com/llm-proxy/llm-proxy/assets/69471761/84027332-216e-4d96-afae-997da485eaef)

**Comment by laxitshahi** [comment]
Update: We want to use a set amount of prompts for the testing. Somewhere around 10-50 prompts. We can utilize the prompts from here:
https://luv-bansal.medium.com/benchmarking-llms-how-to-evaluate-language-model-performance-b5d061cc8679

**Comment by laxitshahi** [comment]
Complete
