### ISSUE TITLE
Familiarization: library development

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#20]
- [x] Create library and test locally
- [x] Figure out how you can deploy the library on pypi

Resources:

1. Create library locally (a thread): https://github.com/orgs/python-poetry/discussions/1135#discussioncomment-145756 
2. Publish library to pipy: https://www.youtube.com/watch?v=Xf8K3v8_JwQ

Relates to #15

**Comment by laxitshahi** [comment]
# Resources
- https://www.youtube.com/watch?v=5KEObONUkik

**Comment by laxitshahi** [comment]
Related to #15 and #97
