### ISSUE TITLE
Implement Claude

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#31]
API not available in Canada (only US?)
- We may need to discuss to Adrien about getting an API from him
- Reference: https://www.anthropic.com/claude-ai-locations

![Image](https://github.com/llm-proxy/llm-proxy/assets/46412618/b56165f8-c991-4c41-86f7-c653a3941921)

**Comment by laxitshahi** [comment]
We are going to utilize @adrienlaurent 's API key
