### ISSUE TITLE
Setup Library Interface

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#52]
- How will the developer add their API keys
- Do we want to utilize a config file
- Sensible defaults or required parameters

**Comment by laxitshahi** [comment]
To Do
- [ ] Setup using yaml
- [ ] Keep params in yaml to allow developer to edit
- [ ] Start with cost classification
- [ ] Keep API keys in .env?

**Comment by laxitshahi** [comment]
#82 takes over this task
