### ISSUE TITLE
Implement Category (Classification) Routing

### ISSUE THREAD

**Issue by laxitshahi** [llm-proxy/llm-proxy#62]
**As a developer**
- **I want** automatic routing for my multiple LLM endpoints based on category
- **So that** I use the most optimal model for my use case and prompt

**Technical Requirements**
- We want a system that will route different LLMs based on the category and best match
- This will require a lightweight* classification algorithm to determine the "category" of the prompt
- This will then be processed and the "best" model will be chosen based on certain flow and constraints
- The flow and decisions made at every step should be logged for the developer to see

**Resources**
- [4 Types of Classification Tasks in Machine Learning](https://get-elevate.com/4-types-of-classification-tasks-in-machine-learning/#:~:text=There%20are%20four%20main%20types,you%20train%20your%20next%20model.)
- [Text Classification Using Naive Bayes](https://www.youtube.com/watch?v=60pqgfT5tZM&ab_channel=Simplilearn)
- [Build Text Classification Model using Word2Vec](https://www.youtube.com/watch?v=P47raNuzAW0&t=604s&ab_channel=PradipNichite)
- [Word2Vec For Text Classification - Article w/ Code](https://spotintelligence.com/2023/02/15/word2vec-for-text-classification/#Word2Vec_CNN_text_classification)

**Comment by dinuja9** [comment]
[] figure out what the different categories are for the LLMs
	- once done, make data file

**Comment by laxitshahi** [comment]
Current integration is:
1. Use of OpenAI
- Impractical resolution 
 - We can't use this for every single user of our library or expect every user to have openai available
2. Custom Model created
- Too slow due to the need for retraining every time there is a request made



Current Solution:
- Look into a way to create a lightweight finetuned mode that is **saved**, so it can be seamlessly integrated
- Ask professor Hemmati techniques/ methods

**Comment by laxitshahi** [comment]
Put category model in a file as a function, as there is not enough reason to make a separate class for it
