### ISSUE TITLE
Enroll and Watch LangChain for LLM Application Development

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#7]
https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/

**Comment by TheVicBro** [comment]
@TheVicBro @BallenAlain @laxitshahi @MohamedAhmed74 @OfficalGlitch @DesNahback @dinuja9 

Due date is before our next meeting on Tuesday.

**Comment by laxitshahi** [comment]
**Updated**

Requested by Adrian:

Watch these 2 courses first:
- https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/
- https://www.deeplearning.ai/short-courses/building-systems-with-chatgpt/

Then watch the langchain video:
- https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/
