### ISSUE TITLE
Fix chat-bison unrecognized model error

### ISSUE THREAD

**Issue by laxitshahi** [llm-proxy/llm-proxy#89]
When using the chat-bison model from vertexai, an error stating the model is not available will pop up:

![Image](https://github.com/llm-proxy/llm-proxy/assets/46412618/3d0d23d0-0742-4e39-9911-2f42a4aed009)

**Comment by laxitshahi** [comment]
Google Cloud trail expired

**Comment by BallenAlain** [comment]
https://github.com/llm-proxy/llm-proxy/pull/152
