### ISSUE TITLE
Error handling refactor

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#95]
- As part of the overall codebase refactor, error handling needs to be refactored to NOT return completion response (rather just throw and error) 

Subtask of #86

**Comment by laxitshahi** [comment]
Errors are bubbled to the top. Emphasis on using custom errors for the sake of clarity and testability

**Comment by laxitshahi** [comment]
Errors are bubbled to the top. Emphasis on using custom errors for the sake of clarity and testability
